### ISSUE TITLE
ranges_df ignores duplicate innacuracies

### ISSUE THREAD

**Issue by half-adder** [ApfeldLab/SensorOverlord#11]
If multiple identical inaccuracies are passed to the ranges_df function, it ignores the second

To reproduce:

```
library(sensorOverlord)
my_sensor <- new("Sensor", Rmin = 0.852, Rmax = 6.65, delta = 0.171)
my_redox_sensor <- new("redoxSensor", my_sensor, e0 = -265)
nrow(ranges_df(my_redox_sensor, inaccuracies = c(0.018, 0.028, 0.018), thresholds=c(1)))
```
Expected output:
3

Actual output:
2

**Comment by julianstanley** [comment]
Nice catch!

So, on lines 445 and 446 of utils.R, I make the assumption that we identify sensor by unique name-inaccuracy pairs. 

I went ahead and added a bit extra at the end of that function to make this work. 

PR #12 (about to merge) should fix that problem:

```r
> library(sensorOverlord)
> my_sensor <- new("Sensor", Rmin = 0.852, Rmax = 6.65, delta = 0.171)
> my_redox_sensor <- new("redoxSensor", my_sensor, e0 = -265)
> nrow(ranges_df(my_redox_sensor, inaccuracies = c(0.018, 0.028, 0.018), thresholds=c(1)))
[1] 3
```
